// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Convert(arg1) {
  return window['go']['main']['App']['Convert'](arg1);
}

export function ConvertSkelToJson(arg1) {
  return window['go']['main']['App']['ConvertSkelToJson'](arg1);
}

export function FindAE() {
  return window['go']['main']['App']['FindAE']();
}

export function LoadSpineFile(arg1) {
  return window['go']['main']['App']['LoadSpineFile'](arg1);
}

export function OpenSpineFile() {
  return window['go']['main']['App']['OpenSpineFile']();
}

export function RunInAE(arg1, arg2) {
  return window['go']['main']['App']['RunInAE'](arg1, arg2);
}

export function UnpackAtlas(arg1, arg2, arg3) {
  return window['go']['main']['App']['UnpackAtlas'](arg1, arg2, arg3);
}
