// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Convert(arg1:main.ConvertOptions):Promise<main.ConvertResult>;

export function ConvertSkelToJson(arg1:string):Promise<string>;

export function FindAE():Promise<string>;

export function LoadSpineFile(arg1:string):Promise<main.SpineInfo>;

export function OpenSpineFile():Promise<string>;

export function RunInAE(arg1:string,arg2:string):Promise<void>;

export function UnpackAtlas(arg1:string,arg2:string,arg3:string):Promise<main.UnpackResult>;
